spring.application.name=backend-miku-quiz

spring.jpa.show-sql=true
spring.jpa.open-in-view=true
server.port=8080
server.address=0.0.0.0

spring.jpa.defer-datasource-initialization=true
spring.datasource.url=${DB_URL:jdbc:postgresql://IP_DO_BANCO_DE_DADOS:5432/mikuquiz}
spring.datasource.username=${DB_USERNAME:postgres}

spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.properties.hibernate.format_sql=true


spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri=URI_ADICIONADA_NO_GOOGLE/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://www.googleapis.com/oauth2/v4/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub



jwt.secret-key=${JWT_SECRET_KEY}
jwt.expiration-ms=3600000

spring.ai.openai.chat.options.timeout=60s
spring.ai.openai.chat.options.connect-timeout=20s

spring.ai.openai.api-key=${OPENAI_API_KEY}